INFO:root:Sincronização realizada com sucesso: 2023-08-18 17:38:12
ERROR:root:Erro ao conectar com o banco de dados offline: 'tuple' object does not support item assignment
ERROR:root:Erro ao conectar com o banco de dados offline: 'tuple' object does not support item assignment
ERROR:root:Erro ao conectar com o banco de dados offline: name 'colunas_reversea' is not defined
ERROR:root:Erro ao conectar com o banco de dados offline: DatabaseManager.delete_data() missing 1 required positional argument: 'condition'
ERROR:root:Erro ao conectar com o banco de dados offline: DatabaseManager.delete_data() missing 1 required positional argument: 'condition'
ERROR:root:Erro ao conectar com o banco de dados offline: Errors occurred during insertion. See logs for details.
ERROR:root:Erro ao conectar com o banco de dados offline: Parar
DEBUG:matplotlib:CACHEDIR=C:\Users\jrmfi\.matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from C:\Users\jrmfi\.matplotlib\fontlist-v330.json
ERROR:root:Erro ao conectar com o banco de dados offline: 1146 (42S02): Table 'railway.cgh_fae' doesn't exist
